services:
  db:
    image: public.ecr.aws/docker/library/postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: jaruser
      POSTGRES_PASSWORD: jarpassword
      POSTGRES_DB: jardb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/privatenesk/py_labelspitter/backend:latest
    restart: always
    environment:
      DATABASE_URL: postgresql://jaruser:jarpassword@db:5432/jardb
      PRINTER_WIDTH_MM: 62
      PRINTER_DPI: 300
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: ghcr.io/privatenesk/py_labelspitter/frontend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_API_BASE: http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
